### ISSUE TITLE
Move travis config to github actions?

### ISSUE THREAD

**Issue by oeway** [deepimagej/models#11]
I noticed that you have two types of CI in the same repo, which can be fine in principle, but you don't have to maintain both of them. What I propose is to remote the travis file, and add the commands into the github actions.

Basically integrate the verification script to the [github actions file](https://github.com/deepimagej/models/blob/master/.github/workflows/compile-manifest.yml).
```yaml
      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/bioimage-io/bioimage-io-models/master/requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/bioimage-io/python-bioimage-io.git@verify_spec
      - name: Verify config files
         run: python -m pybio.spec verify-bioimageio-manifest manifest.bioimage.io.yaml
      - name: Compile manifest file
        run: |
          wget https://raw.githubusercontent.com/bioimage-io/bioimage-io-models/master/src/compile_model_manifest.py
          python compile_model_manifest.py
```
